### ISSUE TITLE
Save Page Now to the Wayback Machine extension

### ISSUE THREAD

**Issue by Gitoffthelawn** [tqdv/tab-events-tab-events#9]
Hello!

I'm searching for the repo for your helpful  "Save Page Now to the Wayback Machine" web extension.  I'm not seeing it in the list of your repos.  Would you mind adding it (and adding a link to the repo on AMO)?

I have an issue I would like to report for it, but have no place to do so.

Thanks so much, and thank you for the wonderfully helpful tools.

**Comment by tqdv** [comment]
Hi!

Thanks for finding my stuff useful. I just uploaded the code for the "Save Page Now" extension on GitHub here:
https://github.com/tqdv/save-page-now.

Have a nice day :slightly_smiling_face:

**Comment by Gitoffthelawn** [comment]
Thank you so much!

I'll make a few edits for you and also post your first "issue" report!

Thanks again!
